from django.contrib import admin
from . import models
# Register your models here.

admin.site.register(models.farmerRegistration)
admin.site.register(models.farmerSearch)
admin.site.register(models.Akola)
admin.site.register(models.Amravati)
admin.site.register(models.Aurangabad)
admin.site.register(models.Beed)
admin.site.register(models.Bhandara)
admin.site.register(models.Buldhana)
admin.site.register(models.Chandrapur)
admin.site.register(models.Dhule)
admin.site.register(models.Gadchiroli)
admin.site.register(models.Gondia)
admin.site.register(models.Hingoli)
admin.site.register(models.Jalgaon)
admin.site.register(models.Jalna)
admin.site.register(models.Kolhapur)
admin.site.register(models.Latur)
admin.site.register(models.Nagpur)
admin.site.register(models.Nanded)
admin.site.register(models.Nandurbar)
admin.site.register(models.Nashik)
admin.site.register(models.Osmanabad)
admin.site.register(models.Parbhani)
admin.site.register(models.Pune)
admin.site.register(models.Raigad)
admin.site.register(models.Ratnagiri)
admin.site.register(models.Sangli)
admin.site.register(models.Satara)
admin.site.register(models.Sindhudurg)
admin.site.register(models.Solapur)
admin.site.register(models.Thane)
admin.site.register(models.Wardha)
admin.site.register(models.Washim)
admin.site.register(models.Yavatmal)
admin.site.register(models.districtCoords)
admin.site.register(models.Crop_List)
admin.site.register(models.seasonEncode)
admin.site.register(models.rainfall2k19)
