# Generated by Django 2.1.3 on 2019-03-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
