# Generated by Django 2.1.3 on 2019-03-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_auto_20190309_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerregistration',
            name='id',
        ),
        migrations.AlterField(
            model_name='farmerregistration',
            name='aadharNumber',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmerregistration',
            name='areaInHectare',
            field=models.SmallIntegerField(),
        ),
    ]
