# Generated by Django 2.1.3 on 2019-03-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_auto_20190309_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='aadharNumber',
            field=models.IntegerField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
