# Generated by Django 2.1.3 on 2019-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_auto_20190309_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='aadharNumber',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
