# Generated by Django 2.1.3 on 2019-03-09 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_auto_20190309_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerregistration',
            name='date_register',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
