# Generated by Django 2.1.3 on 2019-03-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_auto_20190309_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='aadharNumber',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmerregistration',
            name='areaInHectare',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='farmerregistration',
            name='phoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
