# Generated by Django 2.1.3 on 2019-03-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_auto_20190309_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerregistration',
            old_name='aadharNumber',
            new_name='aadhar_Number',
        ),
        migrations.RenameField(
            model_name='farmerregistration',
            old_name='farmerName',
            new_name='farmer_Name',
        ),
        migrations.RenameField(
            model_name='farmerregistration',
            old_name='phoneNumber',
            new_name='phone_Number',
        ),
    ]
