# Generated by Django 2.1.3 on 2019-03-11 06:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0014_auto_20190311_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='phone_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
