# Generated by Django 2.1.3 on 2019-03-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0016_auto_20190311_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='phone_Number',
            field=models.IntegerField(unique=True),
        ),
    ]
