# Generated by Django 2.1.3 on 2019-03-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0017_auto_20190311_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='phone_Number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
