# Generated by Django 2.1.3 on 2019-03-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0019_auto_20190311_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerRequetedDetails',
            fields=[
                ('farmer_Name', models.CharField(max_length=50)),
                ('aadhar_Number', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='farmerregistration',
            name='farmer_Name',
            field=models.CharField(max_length=50),
        ),
    ]
