# Generated by Django 2.1.3 on 2019-03-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0020_auto_20190311_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farmerRequetedDetails',
        ),
    ]
