# Generated by Django 2.1.7 on 2019-03-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0022_farmerregistration_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=20),
        ),
    ]
