# Generated by Django 2.1.7 on 2019-03-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0025_auto_20190312_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerSearch',
            fields=[
                ('farmerName', models.CharField(max_length=50)),
                ('aadharNumber', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('state', models.CharField(default='Maharashtra', max_length=20)),
            ],
        ),
    ]
