# Generated by Django 2.1.7 on 2019-03-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0027_auto_20190315_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='aadhar_Number',
            field=models.IntegerField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
