# Generated by Django 2.1.7 on 2019-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0029_auto_20190327_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='aadhar_Number',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmersearch',
            name='aadharNumber',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
