# Generated by Django 2.1.7 on 2019-03-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0032_auto_20190327_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmersearch',
            old_name='aadharNumber',
            new_name='aadharNum',
        ),
        migrations.RenameField(
            model_name='farmersearch',
            old_name='state',
            new_name='state1',
        ),
    ]
