# Generated by Django 2.1.7 on 2019-03-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0033_auto_20190327_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmersearch',
            old_name='aadharNum',
            new_name='aadharNumber',
        ),
        migrations.RenameField(
            model_name='farmersearch',
            old_name='state1',
            new_name='state',
        ),
    ]
