# Generated by Django 2.1.7 on 2019-03-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0035_auto_20190327_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='aadhar_Number',
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmersearch',
            name='Aadhar',
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
    ]
