# Generated by Django 2.1.7 on 2019-04-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0037_auto_20190327_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmersearch',
            old_name='Aadhar',
            new_name='aadharNumber',
        ),
        migrations.RenameField(
            model_name='farmersearch',
            old_name='Farmer',
            new_name='farmerName',
        ),
        migrations.RenameField(
            model_name='farmersearch',
            old_name='State',
            new_name='state',
        ),
    ]
