# Generated by Django 2.1.7 on 2019-04-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0038_auto_20190402_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='district',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerregistration',
            name='farmer_Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='farmersearch',
            name='farmerName',
            field=models.CharField(max_length=30),
        ),
    ]
