# Generated by Django 2.1.7 on 2019-04-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0039_auto_20190402_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='phone_Number',
            field=models.PositiveSmallIntegerField(max_length=10, unique=True),
        ),
    ]
