# Generated by Django 2.1.7 on 2019-04-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0040_auto_20190402_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmersearch',
            old_name='aadharNumber',
            new_name='aadhar_Number',
        ),
        migrations.RenameField(
            model_name='farmersearch',
            old_name='farmerName',
            new_name='farmer_Name',
        ),
    ]
