# Generated by Django 2.1.7 on 2019-04-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0041_auto_20190402_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='aadhar_Number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmersearch',
            name='aadhar_Number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
