# Generated by Django 2.1.7 on 2019-04-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0042_auto_20190402_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='phone_Number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
