# Generated by Django 2.1.7 on 2019-04-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0045_amravati_aurangabad_beed_bhandara_buldhana_chandrapur_dhule_gadchiroli_gondia_hingoli_jalgaon_jalna_'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Akola',
        ),
    ]
