# Generated by Django 2.1.7 on 2019-04-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0046_delete_akola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_Name', models.CharField(max_length=50)),
                ('ph_Value', models.FloatField()),
                ('N_Value', models.FloatField()),
                ('P_Value', models.FloatField()),
                ('K_Value', models.FloatField()),
                ('OC_Value', models.FloatField()),
                ('Fe_Value', models.FloatField()),
            ],
        ),
    ]
