# Generated by Django 2.1.7 on 2019-04-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0047_akola'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nandurbar',
        ),
    ]
