# Generated by Django 2.1.7 on 2019-04-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0049_nandurbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='districtCoords',
            fields=[
                ('District', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Amravati',
        ),
    ]
