# Generated by Django 2.1.7 on 2019-04-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0051_amravati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='phone_Number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
