# Generated by Django 2.1.7 on 2019-04-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0053_auto_20190404_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='district',
            field=models.CharField(max_length=20),
        ),
    ]
