# Generated by Django 2.1.7 on 2019-04-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0054_auto_20190404_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerregistration',
            name='state',
        ),
        migrations.RemoveField(
            model_name='farmersearch',
            name='state',
        ),
    ]
