# Generated by Django 2.1.7 on 2019-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0055_auto_20190404_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerregistration',
            name='village',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='farmersearch',
            name='village',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
