# Generated by Django 2.1.7 on 2019-04-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0056_auto_20190404_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerregistration',
            old_name='village',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='farmersearch',
            old_name='village',
            new_name='state',
        ),
    ]
