# Generated by Django 2.1.7 on 2019-04-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0057_auto_20190410_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerregistration',
            name='state',
        ),
        migrations.RemoveField(
            model_name='farmersearch',
            name='state',
        ),
    ]
