# Generated by Django 2.1.7 on 2019-04-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0058_auto_20190410_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerregistration',
            name='village',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='farmersearch',
            name='village',
            field=models.CharField(default='', max_length=30),
        ),
    ]
