# Generated by Django 2.1.7 on 2019-04-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0060_farmerdetailsinfomation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farmerDetailsInfomation',
        ),
    ]
