# Generated by Django 2.1.7 on 2019-04-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0061_delete_farmerdetailsinfomation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solhapur',
            new_name='Solapur',
        ),
    ]
