# Generated by Django 2.1.7 on 2019-04-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0062_auto_20190413_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=30)),
                ('crop_Arhar', models.SmallIntegerField()),
                ('crop_Bajra', models.SmallIntegerField()),
                ('crop_Cotton', models.SmallIntegerField()),
                ('crop_Gram', models.SmallIntegerField()),
                ('crop_Groundnut', models.SmallIntegerField()),
                ('crop_Jowar', models.SmallIntegerField()),
                ('crop_Maize', models.SmallIntegerField()),
                ('crop_Moong', models.SmallIntegerField()),
                ('crop_Mustard', models.SmallIntegerField()),
                ('crop_Nigerseed', models.SmallIntegerField()),
                ('crop_Ragi', models.SmallIntegerField()),
                ('crop_Rice', models.SmallIntegerField()),
                ('crop_Safflower', models.SmallIntegerField()),
                ('crop_Sesamum', models.SmallIntegerField()),
                ('crop_Soyabean', models.SmallIntegerField()),
                ('crop_Sugarcane', models.SmallIntegerField()),
                ('crop_Sunflower', models.SmallIntegerField()),
                ('crop_Urad', models.SmallIntegerField()),
                ('crop_Wheat', models.SmallIntegerField()),
                ('time_to_Grow', models.SmallIntegerField()),
                ('season', models.CharField(max_length=20)),
            ],
        ),
    ]
