# Generated by Django 2.1.7 on 2019-04-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0064_auto_20190413_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop_List',
        ),
    ]
