# Generated by Django 2.1.7 on 2019-04-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0065_delete_crop_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='seasonEncode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonName', models.CharField(max_length=20)),
                ('kharif', models.IntegerField()),
                ('rabi', models.IntegerField()),
                ('wholeYear', models.IntegerField()),
            ],
        ),
    ]
