# Generated by Django 2.1.7 on 2019-04-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0066_seasonencode'),
    ]

    operations = [
        migrations.CreateModel(
            name='rainfall2k19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30)),
                ('rainfall', models.FloatField()),
            ],
        ),
    ]
