# Generated by Django 2.1.7 on 2019-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0069_auto_20190413_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Arhar',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Bajra',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Cotton',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Gram',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Groundnut',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Jowar',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Maize',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Moong',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Mustard',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Nigerseed',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Ragi',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Rice',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Safflower',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Sesamum',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Soyabean',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Sugarcane',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Sunflower',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Urad',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='crop_Wheat',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='crop_list',
            name='time_to_Grow',
            field=models.CharField(max_length=4),
        ),
    ]
