# Generated by Django 2.2 on 2019-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0070_auto_20190413_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainfall2k19',
            name='id',
        ),
        migrations.RemoveField(
            model_name='seasonencode',
            name='id',
        ),
        migrations.AlterField(
            model_name='rainfall2k19',
            name='district',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seasonencode',
            name='seasonName',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
