# Generated by Django 2.2 on 2019-04-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0071_auto_20190413_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Akola',
        ),
        migrations.DeleteModel(
            name='Amravati',
        ),
        migrations.DeleteModel(
            name='Aurangabad',
        ),
        migrations.DeleteModel(
            name='Beed',
        ),
        migrations.DeleteModel(
            name='Bhandara',
        ),
        migrations.DeleteModel(
            name='Buldhana',
        ),
        migrations.DeleteModel(
            name='Chandrapur',
        ),
        migrations.DeleteModel(
            name='Dhule',
        ),
        migrations.DeleteModel(
            name='Gadchiroli',
        ),
        migrations.DeleteModel(
            name='Gondia',
        ),
        migrations.DeleteModel(
            name='Hingoli',
        ),
        migrations.DeleteModel(
            name='Jalgaon',
        ),
        migrations.DeleteModel(
            name='Jalna',
        ),
        migrations.DeleteModel(
            name='Kolhapur',
        ),
        migrations.DeleteModel(
            name='Latur',
        ),
        migrations.DeleteModel(
            name='Nagpur',
        ),
        migrations.DeleteModel(
            name='Nanded',
        ),
        migrations.DeleteModel(
            name='Nandurbar',
        ),
        migrations.DeleteModel(
            name='Nashik',
        ),
        migrations.DeleteModel(
            name='Osmanabad',
        ),
        migrations.DeleteModel(
            name='Parbhani',
        ),
        migrations.DeleteModel(
            name='Pune',
        ),
        migrations.DeleteModel(
            name='Raigad',
        ),
        migrations.DeleteModel(
            name='Ratnagiri',
        ),
        migrations.DeleteModel(
            name='Sangli',
        ),
        migrations.DeleteModel(
            name='Satara',
        ),
        migrations.DeleteModel(
            name='Sindhudurg',
        ),
        migrations.DeleteModel(
            name='Solapur',
        ),
        migrations.DeleteModel(
            name='Thane',
        ),
        migrations.DeleteModel(
            name='Wardha',
        ),
        migrations.DeleteModel(
            name='Washim',
        ),
        migrations.DeleteModel(
            name='Yavatmal',
        ),
    ]
