# Generated by Django 2.2 on 2019-04-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0073_akola_amravati_aurangabad_beed_bhandara_buldhana_chandrapur_dhule_gadchiroli_gondia_hingoli_jalgaon_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akola',
            name='id',
        ),
        migrations.RemoveField(
            model_name='amravati',
            name='id',
        ),
        migrations.RemoveField(
            model_name='aurangabad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='beed',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bhandara',
            name='id',
        ),
        migrations.RemoveField(
            model_name='buldhana',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chandrapur',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dhule',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gadchiroli',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gondia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hingoli',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jalgaon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jalna',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kolhapur',
            name='id',
        ),
        migrations.RemoveField(
            model_name='latur',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nagpur',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nanded',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nandurbar',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nashik',
            name='id',
        ),
        migrations.RemoveField(
            model_name='osmanabad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parbhani',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pune',
            name='id',
        ),
        migrations.RemoveField(
            model_name='raigad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ratnagiri',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sangli',
            name='id',
        ),
        migrations.RemoveField(
            model_name='satara',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sindhudurg',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solapur',
            name='id',
        ),
        migrations.RemoveField(
            model_name='thane',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wardha',
            name='id',
        ),
        migrations.RemoveField(
            model_name='washim',
            name='id',
        ),
        migrations.RemoveField(
            model_name='yavatmal',
            name='id',
        ),
        migrations.AlterField(
            model_name='akola',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amravati',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aurangabad',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beed',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bhandara',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buldhana',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chandrapur',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dhule',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gadchiroli',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gondia',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hingoli',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jalgaon',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jalna',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kolhapur',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='latur',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nagpur',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nanded',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nandurbar',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nashik',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='osmanabad',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parbhani',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pune',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='raigad',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ratnagiri',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sangli',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='satara',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sindhudurg',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solapur',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thane',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wardha',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='washim',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yavatmal',
            name='village_Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
