# Generated by Django 2.2 on 2019-04-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0074_auto_20190413_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop_List',
        ),
    ]
