# Generated by Django 2.2 on 2019-04-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0077_auto_20190413_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop_List',
        ),
    ]
